### ISSUE TITLE
New Hackage release?

### ISSUE THREAD

**Issue by dhess** [valderman/selda#187]
Hi, thanks for this project!

With the recent support for GHC 9.4.4 and text > 2, it would be helpful if there were a release to Hackage that included these new features. Is that feasible in the near future?

**Comment by dhess** [comment]
Ideally a new release would include #188, as well.

**Comment by tomasaschan** [comment]
@dhess You mentioned [here](https://github.com/hackworthltd/primer/issues/499#issuecomment-1658081545) that you re-introduced `selda` in your project. Did that include a patch to support text >2? If so, how did you get that - build this library from source, or install through other means than hackage?

**Comment by dhess** [comment]
@tomasaschan Here's what we're using:

https://github.com/hackworthltd/primer/blob/9e4d489a050207420669cd9b5bd9efeb40ffee8f/cabal.project#L29

**Comment by tomasaschan** [comment]
@dhess Thanks a bunch! That seems to work for me too; although I'm using `stack`, so I put this in my stack.yaml (and added `selda` and `selda-sqlite` to my dependencies):
```yaml
extra-deps:
- git: https://github.com/guibou/selda
  commit: ab9619db13b93867d1a244441bb4de03d3e1dadb
  subdirs:
  - selda
  - selda-sqlite
```
Worked like a charm (at least for building with the deps included.. 🤞🏻)
